#!/usr/bin/env bash
#this is a comment
while IFS=: read -r username _ userid _ _ homedir _
do
    # Print exactly in the format required
    printf "User: %s, UID: %s, Home: %s\n" "$username" "$userid" "$homedir"
done < /etc/passwd
