#!/usr/bin/env bash
# This script reads from standard input, so it can be used with a pipe.
awk 'NF >= 8 { 
    print $1, (NF == 8 ? $7 : (NF == 9 ? $8 : $9)) 
}' apache-access.log | LC_ALL=C sort | LC_ALL=C uniq -c | LC_ALL=C sort -nr

