#!/usr/bin/env bash
# This script reads from standard input, so it can be used with a pipe.
awk '
NF >= 9 {
    counts[$1 " " $9]++
}
END {
    for (key in counts) {
        print counts[key], key
    }
}
' | sort -nr
