#!/usr/bin/env bash
# this is a comment
hour=0

while [ $hour -le 12 ]
do
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$hour:$minute"
    minute=$((minute + 1))
  done
  hour=$((hour + 1))
done
